'use client';
import * as React from 'react';

const reviews=[
{n:'Healthcare Website Owner',s:'Healthcare WordPress build',r:'Fast, responsive and clear communication. The final WordPress site made our services easier to understand and helped us present a more trustworthy healthcare brand.'},
{n:'Travel Business Client',s:'Travel / booking website',r:'Adeel understood the booking flow properly and converted the idea into a clean, mobile-friendly experience. The package sections and CTAs became much easier for customers.'},
{n:'Corporate Services Founder',s:'Corporate Elementor website',r:'The website structure became much more professional. Services, trust sections and inquiry flow were handled with strong attention to detail.'},
{n:'Local Service Brand',s:'Local business website',r:'The build felt clean, practical and conversion-focused. Mobile spacing, contact buttons and service sections were improved in a way that helps visitors take action.'},
{n:'Agency Collaboration',s:'WordPress fixes and support',r:'Reliable WordPress support, clean Elementor work and solid troubleshooting. Adeel is easy to work with when a site needs practical fixes and launch support.'}
];

function Stars(){return <div style={{display:'flex',gap:4,color:'#F6C945',fontSize:20,marginBottom:22}} aria-label="5 out of 5 stars">{Array.from({length:5}).map((_,i)=><span key={i}>★</span>)}</div>}

export default function Testimonials(){return <section className="section" style={{background:'radial-gradient(circle at 15% 10%,#f6c94533,transparent 28%),radial-gradient(circle at 82% 8%,#9b6cff33,transparent 26%)'}}><div className="wrap" style={{display:'grid',gridTemplateColumns:'minmax(0,.95fr) minmax(0,1.15fr)',gap:56,alignItems:'start'}}><div style={{position:'sticky',top:120}}><span className="eyebrow">Client Feedback</span><h2 className="title">Testimonials that show the value behind the build</h2><p className="muted">Draft review cards for the portfolio. Replace the names with verified client names whenever you want to publish real testimonials.</p><div className="chips"><span className="chip">5.0 quality mindset</span><span className="chip">Responsive support</span><span className="chip">Client-ready delivery</span></div></div><div style={{position:'relative',minHeight:980,perspective:1000}}>{reviews.map((t,i)=><article key={t.n} style={{position:'sticky',top:118,marginBottom:26,minHeight:300,border:'1px solid var(--line)',borderRadius:34,background:'color-mix(in srgb,var(--surface) 82%,transparent)',backdropFilter:'blur(18px)',boxShadow:'0 28px 90px #0000001f',padding:34,display:'flex',flexDirection:'column',justifyContent:'space-between',transform:`translateY(${i*16}px) rotate(${(i-2)*-2}deg)`,zIndex:10-i}}><div><Stars/><p style={{fontSize:'clamp(1.35rem,2.7vw,2.4rem)',lineHeight:1.08,letterSpacing:'-.045em',fontWeight:900,margin:0}}>“{t.r}”</p></div><div style={{display:'flex',alignItems:'end',justifyContent:'space-between',borderTop:'1px solid var(--line)',paddingTop:22,marginTop:34}}><div><b style={{display:'block',fontSize:18}}>{t.n}</b><span style={{display:'block',color:'var(--muted)',marginTop:5}}>{t.s}</span></div><small style={{fontWeight:950,fontSize:42,letterSpacing:'-.08em',color:'color-mix(in srgb,var(--text) 24%,transparent)'}}>0{i+1}</small></div></article>)}</div></div></section>}
