'use client';
import * as React from 'react';
import {cva,type VariantProps} from 'class-variance-authority';
import {motion,type HTMLMotionProps,type MotionValue,useMotionTemplate,useMotionValueEvent,useScroll,useTransform} from 'motion/react';
import {cn} from '@/lib/utils';

const cardVariants=cva('absolute will-change-transform',{variants:{variant:{dark:'flex size-full flex-col items-center justify-center gap-6 rounded-2xl border border-stone-700/50 bg-accent-foreground/80 p-6 text-background backdrop-blur-md',light:'flex size-full flex-col items-center justify-center gap-6 rounded-2xl border bg-accent p-6 text-foreground backdrop-blur-md'}},defaultVariants:{variant:'light'}});
interface Ctx{scrollYProgress:MotionValue<number>}
const ContainerScrollContext=React.createContext<Ctx|undefined>(undefined);
function useContainerScrollContext(){const c=React.useContext(ContainerScrollContext);if(!c)throw new Error('ContainerScroll context missing');return c}
export function ContainerScroll({children,style,className,...props}:React.HTMLAttributes<HTMLDivElement>){const scrollRef=React.useRef<HTMLDivElement>(null);const{scrollYProgress}=useScroll({target:scrollRef,offset:['start center','end end']});return <ContainerScrollContext.Provider value={{scrollYProgress}}><div ref={scrollRef} className={cn('relative min-h-svh w-full',className)} style={{perspective:'1000px',...style}} {...props}>{children}</div></ContainerScrollContext.Provider>}
export function CardsContainer({children,className,...props}:React.HTMLAttributes<HTMLDivElement>){return <div className={cn('relative isolate',className)} style={{perspective:'1000px',...props.style}} {...props}>{children}</div>}
interface CardStickyProps extends HTMLMotionProps<'div'>,VariantProps<typeof cardVariants>{arrayLength:number;index:number;incrementY?:number;incrementZ?:number;incrementRotation?:number}
export const CardTransformed=React.forwardRef<HTMLDivElement,CardStickyProps>(({arrayLength,index,incrementY=10,incrementZ=10,incrementRotation=-index+90,className,variant,style,...props},ref)=>{const{scrollYProgress}=useContainerScrollContext();const[activeIndex,setActiveIndex]=React.useState(1);useMotionValueEvent(scrollYProgress,'change',(latest)=>{const active=Math.max(1,Math.min(arrayLength,Math.floor(latest*(arrayLength+1))));setActiveIndex(active)});const start=index/(arrayLength+1);const end=(index+1)/(arrayLength+1);const range=React.useMemo(()=>[start,end],[start,end]);const rotateRange=[range[0]-1.5,range[1]/1.5];const y=useTransform(scrollYProgress,range,['0%','-180%']);const rotate=useTransform(scrollYProgress,rotateRange,[incrementRotation,0]);const transform=useMotionTemplate`translateZ(${index*incrementZ}px) translateY(${y}) rotate(${rotate}deg)`;const dx=useTransform(scrollYProgress,rotateRange,[4,0]);const dy=useTransform(scrollYProgress,rotateRange,[4,12]);const blur=useTransform(scrollYProgress,rotateRange,[2,24]);const alpha=useTransform(scrollYProgress,rotateRange,[0.15,0.2]);const filter=variant==='light'?useMotionTemplate`drop-shadow(${dx}px ${dy}px ${blur}px rgba(0,0,0,${alpha}))`:'none';const zIndex=index<=activeIndex?1000+index*incrementZ:(arrayLength-index)*incrementZ;return <motion.div layout="position" ref={ref} style={{top:index*incrementY,transform,backfaceVisibility:'hidden',zIndex,filter,...style}} className={cn(cardVariants({variant,className}))} {...props}/>});
CardTransformed.displayName='CardTransformed';
export const ReviewStars=React.forwardRef<HTMLDivElement,{rating:number;maxRating?:number;className?:string}>(({rating,maxRating=5,className,...props},ref)=>{const full=Math.floor(rating);return <div ref={ref} className={cn('flex items-center gap-1',className)} aria-label={`${rating} out of ${maxRating} stars`} {...props}>{Array.from({length:maxRating}).map((_,i)=><span key={i} className={i<full?'text-inherit':'text-gray-300'}>★</span>)}<span className="sr-only">{rating}</span></div>});
ReviewStars.displayName='ReviewStars';
